spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:/healthcare-application
    driver-class-name: org.h2.Driver
    username: pixeon
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default
