spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./healthcare-database-h2/main
    driver-class-name: org.h2.Driver
    username: pixeon
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default
