INSERT INTO HEALTHCARE_INSTITUTION (ID, CNPJ, COIN, NAME)
VALUES (1, '85.129.487/0001-60', 20.0, 'Instituição de saúde Maternal');
INSERT INTO COIN(ID, HEALTHCARE_INSTITUTION_ID, CURRENT_BALANCE, NEW_BALANCE, OPERATION, VALUE_OPERATION,
                 DATE_OPERATION)
VALUES (1, 1, 0.0, 20.0, 'CREDIT', 20.0, CURRENT_TIMESTAMP());